/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class JFramelogin extends javax.swing.JFrame {

    /**
     * Creates new form JFramelogin
     */
    
    private static String USERNAME = null, NAMA_USER = null;
    
    public boolean logins(String usernameOrID, String password){
        USERNAME = usernameOrID;
        try{
            
            String query = 
String.format("SELECT tbl_karyawan.kd_karyawan, tbl_karyawan.nama_karyawan, tbl_login.username, tbl_login.password FROM tbl_karyawan JOIN tbl_login ON tbl_karyawan.kd_karyawan = tbl_login.kd_karyawan WHERE tbl_login.username = '%s' OR tbl_karyawan.kd_karyawan = '%s'", USERNAME, usernameOrID);
            
            Connection conn = (Connection) koneksi.configDB();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(query);
            
            if(res.next()){
                
                if(password.equals(res.getString("tbl_login.password"))){
                    JFramelogin.NAMA_USER = res.getString("tbl_karyawan.nama_karyawan");
                   
                    conn.close();
                    return true;
                }else{
//                    Message.showWarning(this, "Password Anda tidak cocok!");
                    JOptionPane.showMessageDialog(null, "Password Anda tidak cocok!");
                }
            }else{
//                Message.showWarning(this, String.format("'%s' Username tersebut tidak ditemukan!", usernameOrID));
                JOptionPane.showMessageDialog(null, "'%s' Username tersebut tidak ditemukan");
            }
        }catch(SQLException ex){
//            Message.showException(this, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        return false;
    }
    public JFramelogin() {
        initComponents();
        this.jButton2.setBackground(new java.awt.Color(0,0,0,0));
           this.jButton1.setBackground(new java.awt.Color(0,0,0,0));
           this.jButton2.setBackground(new java.awt.Color(0,0,0,0));
           this.teksusername.setBackground(new java.awt.Color(0,0,0,0));
           this.tekspassword.setBackground(new java.awt.Color(0,0,0,0));
           this.butonlupapass.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonlupapass = new javax.swing.JButton();
        teksusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tekspassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonlupapass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonlupapassActionPerformed(evt);
            }
        });
        getContentPane().add(butonlupapass, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 780, 180, 40));

        teksusername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksusername.setBorder(null);
        getContentPane().add(teksusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 578, 520, 60));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 910, 340, 90));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 910, 330, 90));

        tekspassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tekspassword.setBorder(null);
        getContentPane().add(tekspassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 690, 520, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/LANDING PAGE(LOGIN).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        
//        User user = new User();
      
        // mendapatkan data dari textfield
//        String username = this.teksusername.getText(),
//               password = this.tekspassword.getText();
//        // login
//        if(logins(username, password)){
//            // membuka window dashboard jika login berhasil
//            java.awt.EventQueue.invokeLater(new Runnable(){
//                public void run(){
//                    new JFrameDashboard().setVisible(true);
//                }
//            });
//            this.setVisible(false);
//        }
//        
          try {
             String userAkun = teksusername.getText(),
                     passAkun = tekspassword.getText();
            String sql = "SELECT * FROM akun WHERE username = '" + userAkun + "' " + "AND pass = '" + passAkun + "' ";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String namaAkun = r.getString("nama");
               String userAcount = r.getString("username");
               String passAcount = r.getString("pass");
                        
                if(userAkun.equals(userAcount) && passAkun.equals(passAcount)){
                    String upsql = "UPDATE session_login SET nama = '" + namaAkun + "' WHERE kode_sesi = 1";
                    s.executeUpdate(upsql);
                    JOptionPane.showMessageDialog(this, "selamat datang " + namaAkun + " !!!");
                    new JFrameDashboard().setVisible(true);
                    dispose();             
                }
            }else{
                    JOptionPane.showMessageDialog(this, "username atau password salah");
                    System.out.println("salahhh");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new NewJFrameRegister().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butonlupapassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonlupapassActionPerformed
        // TODO add your handling code here:
        new JFramelupapass().setVisible(true);
        dispose();
    }//GEN-LAST:event_butonlupapassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonlupapass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField tekspassword;
    private javax.swing.JTextField teksusername;
    // End of variables declaration//GEN-END:variables
}
