/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class NewJFrameRegister extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameRegister
     */
    public NewJFrameRegister() {
        initComponents();
        this.teksnama.setBackground(new java.awt.Color(0,0,0,0));
        this.teksnotelp.setBackground(new java.awt.Color(0,0,0,0));
        this.teksusername.setBackground(new java.awt.Color(0,0,0,0));
        this.jPasswordField1.setBackground(new java.awt.Color(0,0,0,0));
        this.buttonregister.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonregister = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        teksusername = new javax.swing.JTextField();
        teksnotelp = new javax.swing.JTextField();
        teksnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonregisterActionPerformed(evt);
            }
        });
        getContentPane().add(buttonregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 950, 320, 90));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 520, 60));

        teksusername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksusername.setBorder(null);
        teksusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksusernameActionPerformed(evt);
            }
        });
        getContentPane().add(teksusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 520, 60));

        teksnotelp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksnotelp.setBorder(null);
        getContentPane().add(teksnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 520, 60));

        teksnama.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksnama.setBorder(null);
        getContentPane().add(teksnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 520, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/REGISTER.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1917, -1));

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 630, 70, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teksusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksusernameActionPerformed

    private void buttonregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonregisterActionPerformed
        // TODO add your handling code here:
        if (this.jPasswordField1.getText().length() < 8){
                JOptionPane.showMessageDialog(this, "password minimal harus 8 karakter");
            }else if (this.teksusername.getText().length() < 6){
                JOptionPane.showMessageDialog(this, "username minimal harus 6 karakter");
            }else if (this.teksnama.getText().length() < 2){
                JOptionPane.showMessageDialog(this, "nama minimal harus 2 karakter");
            }else{
                
                    try {
                   String namaUser = this.teksnama.getText(),
                          telpUser = this.teksnotelp.getText(),
                          usernameUser = this.teksusername.getText(),
                          passUser = this.jPasswordField1.getText();
                  String sql = "SELECT * FROM akun WHERE username = '" + usernameUser + "' ";
                  Connection c = (Connection) koneksi.configDB();
                  Statement s = c.createStatement();
                  ResultSet r = s.executeQuery(sql);
                  if(r.next()){
                     String userAcount = r.getString("username");
                      if(usernameUser.equals(userAcount)){
                          JOptionPane.showMessageDialog(this, "username tidak tersedia");
                      }
                  }else{
                       String inpsql = "INSERT INTO akun(username, pass, nama, telepon, token) VALUES (?, ?, ?, ?, ?)";
                      PreparedStatement pst = c.prepareStatement(inpsql);

                     pst.setString(1, usernameUser);
                     pst.setString(2, passUser);
                     pst.setString(3, namaUser);
                     pst.setString(4, telpUser);

                  // make token
                      String rand = "abcdefghijklmnopqrstuvwxyz".toUpperCase();
                      int range = (rand.length()) ;
                      String Result = "";
                      for (int i = 0; i < 6; i++) {
                          int getValue = (int)(Math.random() * range);
                          char CharPoss = rand.charAt(getValue);
                          Result += CharPoss;
                      }

                      pst.setString(5, Result);
                     pst.executeUpdate();

                     c.close();
                     this.teksnama.setText("");
                     this.teksnotelp.setText("");
                     this.teksusername.setText("");
                     this.jPasswordField1.setText("");
                     JOptionPane.showMessageDialog(rootPane, "Daftar berhasil");
                     TimeUnit.SECONDS.sleep(2);
                     new JFramelogin().setVisible(true);
                       dispose();
                      }
              } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, e.getMessage());
              }
         
            }
    }//GEN-LAST:event_buttonregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField teksnama;
    private javax.swing.JTextField teksnotelp;
    private javax.swing.JTextField teksusername;
    // End of variables declaration//GEN-END:variables
}
